config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, controllers: { sessions: :sessions },
             path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root to: 'tests#index'

    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :categories
    resources :gists, only: :index
  end
end

app/models/badge.rb
# == Schema Information
#
# Table name: badges
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  image      :string           not null
#  rule_type  :string           not null
#  rule_value :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Badge < ApplicationRecord
  TYPES = %w(Category Level Attempt).freeze

  validates :title, :image, :rule_type, :rule_value, presence: true
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[edit update destroy show]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_badge_not_found

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule_type, :rule_value)
  end

  def rescue_with_badge_not_found
    flash[:warning] = "Badge not found"

    redirect_to admin_root_path
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!
  def index
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_image(badge)
    image_tag(badge.image, height: "42", width: "42")
  rescue Sprockets::Rails::Helper::AssetNotFound
    'Изображения не найдено'
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= link_to badge.title, admin_badge_path(badge) %></td>
  <td><%= badge_image(badge) %></td>
  <td><%= badge.rule_type %></td>
  <td><%= badge.rule_value %></td>
  <td><%= link_to "Edit", edit_admin_badge_path(badge) %></td>
  <td><%= link_to "Delete", admin_badge_path(badge),
                  method: :delete, data: { confirm: "Are you sure?" } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </p>

  <p>
    <%= form.label :image %>
    <%= form.text_field :image, required: true %>
  </p>

  <p>
    <%= form.label :rule_type %>
    <%= form.select :rule_type, options_for_select(Badge::TYPES, selected: form.object.rule_type) %>
  </p>

  <p>
    <%= form.label :rule_value %>
    <%= form.text_field :rule_value, required: true%>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit badge <%= @badge.title %></h1>
<%= render "form" %>
<%= link_to "Back", admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1>Badges list:</h1>
<%= link_to "New badge", new_admin_badge_path %>
<Table>
  <tr>
    <th>Tilte:</th>
    <th>Image:</th>
    <th>Type:</th>
    <th>Value:</th>

    <th colspan="2">Actions</th>
  </tr>

  <%= render @badges %>
</Table>
<%= link_to "Back", admin_root_path %>

app/views/admin/badges/new.html.erb
<h1>Create new badge</h1>
<%= render "form" %>
<%= link_to "Back", admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong>Badge:</strong>
  <%= @badge.title%>
</p>

<p>
  <strong>Image:</strong>
  <%= @badge.image%>
</p>

<p>
  <strong>Type:</strong>
  <%= @badge.rule_type%>
</p>

<p>
  <strong>Value:</strong>
  <%= @badge.rule_value%>
</p>

<%= link_to "Back", admin_badges_path %>