config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, controllers: { sessions: :sessions },
             path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root to: 'tests#index'

    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :categories
    resources :gists, only: :index
  end
end

app/views/admin/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "TestGuru", root_path %></h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to t('.link_to_tests'), admin_tests_path, class: "p-2 text-dark" %>
    <%= link_to t('.link_to_categoties'), admin_categories_path, class: "p-2 text-dark" %>
    <%= link_to t('.link_to_badges'), admin_badges_path, class: "p-2 text-dark" %>
    <%= link_to 'Gist', admin_gists_path, class: "p-2 text-dark" %>
  </nav>

  <%= link_to t('.logout'), destroy_user_session_path, method: "delete", class: "btn btn-outline-primary" %>
</div>