config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, controllers: { sessions: :sessions },
             path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root to: 'tests#index'

    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :categories
    resources :gists, only: :index
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true
  validates :title, uniqueness: true

  default_scope { order(title: :asc) }

  scope :title, -> (title) { where(title: title) }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :find_category, only: %i[edit update destroy show]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_category_not_found

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to admin_categories_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end

  def rescue_with_category_not_found
    flash[:warning] = "Category not found"

    redirect_to tests_path
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= link_to category.title, admin_category_path(category) %></td>
  <td><%= link_to "Edit", edit_admin_category_path(category) %></td>
  <td><%= link_to "Delete", admin_category_path(category),
                  method: :delete, data: { confirm: "Are you sure?" } %></td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_with model: [:admin, @category], local: true do |form| %>
  <%= render 'shared/errors', resource: @category %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit category <%= @category.title %></h1>
<%= render "form" %>
<%= link_to "Back", admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Categories list:</h1>
<%= link_to "New category", new_admin_category_path %>
<Table>
  <tr>
    <th>Tilte:</th>
    <th colspan="2">Actions</th>
  </tr>

  <%= render @categories %>
</Table>
<%= link_to "Back", admin_tests_path %>

app/views/admin/categories/new.html.erb
<h1>Create new category</h1>
<%= render "form" %>
<%= link_to "Back", admin_categories_path %>

app/views/admin/categories/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @category.title%>
</p>

Tests list:
<Table>
  <% @category.tests.each do |test| %>
    <tr>
      <td><%= link_to test.title, admin_test_path(test) %></td>
    </tr>
  <% end %>
</Table>
<%= link_to "Back", admin_categories_path %>