config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, controllers: { sessions: :sessions },
             path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, only: :index, shallow: true

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root to: 'tests#index'

    resources :badges

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :categories
    resources :gists, only: :index
  end
end

app/views/layouts/_footer.html.erb
<footer class="my-5 pt-1 text-muted text-center text-small">
  <p class="mb-1">
    <%= t('.description') %>
  </p>
  <p class="mb-1">
    &copy; <%= current_year %>
    <%= github_url "KhIgorLe", "test_guru", target: '_blank' %>
  </p>
  <ul class="list-inline">
    <li class="list-inline-item">
      <%= link_to t('.link_to_thinknetica'), " https://thinknetica.com", target: '_blank' %>
    </li>
    <li class="list-inline-item">
      <%= link_to t('.link_to_feedback'), new_feedback_path, target: '_blank' %>
    </li>
  </ul>
</footer>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "TestGuru", root_path %></h5>
  <% if user_signed_in?  %>
    <% if current_user.admin? %>
      <%= link_to t('.control_panel'), admin_tests_path, class: "p-2 text-dark" %>
    <% end %>
    <%= link_to t('.link_to_badges'), badges_path, class: "p-2 text-dark"%>
    <%= link_to t('.logout'), destroy_user_session_path, method: "delete", class: "btn btn-outline-primary" %>
  <% else %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to t('.login'), new_user_session_path, class: "p-2 text-dark" %>
      <%= link_to t('.sign_up'), new_user_registration_path, class: "p-2 text-dark" %>
    </nav>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGuru</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'admin/nav' %>

<div class="container">
  <%= render 'shared/flash' %>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>